# Site settings
title: You Blog                     #你博客的标题
SEOTitle: 临渊羡鱼,不如退而结网        #显示在浏览器上搜索的时候显示的标题
header-img: img/post-bg-rwd.jpg     #显示在首页的背景图片
email: You@gmail.com    
description: "You Blog"              #网站介绍
keyword: "BY, BY Blog, 张爽的博客, qiubaiying, 张爽 A" #关键词
url: "https://zhangshua711.github.io"          # 这个就是填写你的博客地址
baseurl: ""      # 这个我们不用填写
